config/routes.rb
Rails.application.routes.draw do
  root 'top#main'
  resources :products, only: %i[index new create destroy]
  resources :cart_items, only: %i[new create destroy]
  resources :carts, only: %i[show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_items
  has_many :products, through: :cart_items 
  
  def total_balance
    cart_items.inject(0) {|total, item| total += (item.product.price * item.qty) }
  end
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :product
  
  validates :qty, presence: true, numericality: { greater_than: 0, only_integer: true }
end

app/models/product.rb
class Product < ApplicationRecord
  has_one :cart_item, dependent: :destroy
  
  validates :name, presence: true
  validates :price, presence: true, numericality: { greater_than: 0, only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  private
  
  def current_cart
    if session[:cart_id]
      cart = Cart.find(session[:cart_id])
    else
      cart = Cart.create
      session[:cart_id] = cart.id
    end
    cart
  end
  
  helper_method :current_cart
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  def new
    @product = Product.find(params[:product_id])
    @cart_item = CartItem.new
  end
  
  def create
    @product = Product.find(params[:cart_item][:product_id])
    @cart_item = CartItem.new(qty: params[:cart_item][:qty], product_id: params[:cart_item][:product_id], cart_id: params[:cart_item][:cart_id])
    if @cart_item.save!
      flash[:notice] = '商品をカートに追加しました'
      redirect_to current_cart
    else
      flash[:notice] = '商品をカートに追加できませんでした'
      render 'new'
    end
  end
  
  def destroy
    @cart_item = CartItem.find(params[:id])
    if @cart_item.destroy
      flash[:notice] = '商品をカートから削除しました'
    else
      flash[:notice] = '商品をカートから削除できませんでした'
    end
    redirect_to current_cart
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @cart = current_cart
    @total_balance = @cart.total_balance
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all 
  end
  
  def new
    @product = Product.new
  end
  
  def create
    @product = Product.new(name: params[:product][:name], price: params[:product][:price])
    if @product.save
      flash[:notice] = '商品を追加しました'
      redirect_to root_path
    else
      flash[:notice] = '商品の追加に失敗しました'
      render 'new'
    end
  end
  
  def destroy
    @product = Product.find(params[:id])
    if @product.destroy
      flash[:notice] = '商品を削除しました'
    else
      flash[:notice] = '商品を削除できませんでした'
    end
    redirect_to products_path
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def main
    redirect_to products_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/cart_items/new.html.erb
<h2> カートに追加 </h2>

<%= form_for @cart_item, url: { action: :create } do |f| %>
    <p> 商品名: <%= @product.name %> </p>
    <p> 価格: <%= @product.price %> </p>
    <p>
        <%= f.label :qty, '数量' %>
        <%= f.number_field :qty %>
    </p>
    
    <%= f.hidden_field :product_id, value: @product.id %>
    <%= f.hidden_field :cart_id, value: current_cart.id %>
    
    <%= f.submit '商品を追加する' %>
<% end %>

<p> <%= link_to '商品一覧' , products_path %> </p>
<p> <%= link_to 'カートを見る' , cart_path(current_cart) %> </p>

app/views/carts/show.html.erb
<h2> カート一覧 </h2>

<% @cart.cart_items.each do |item| %>
    <div>
        <%= item.product.name %> - ¥<%= item.product.price %> - <%= item.qty %>個
        <%= link_to 'カートから削除', cart_item_path(item.id), method: :delete %>
    </div>
<% end %>

<p> 合計金額: <%= @total_balance %>円 </p>

<p> <%= link_to '商品一覧' , products_path %> </p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>L6</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice] %>
        <p><%= flash[:notice] %></p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/products/index.html.erb
<h2> 商品一覧 </h2>

<% @products.each do |product| %>
    <div>
        <%= product.name %> - ¥<%= product.price %>
        <%= link_to '削除', product_path(product.id), method: :delete %>
        <%= link_to 'カート追加', new_cart_item_path(product_id: product.id)%>
    </div>
<% end %>

<p> <%= link_to '商品を追加する' , new_product_path %> </p>
<p> <%= link_to 'カートを見る' , cart_path(current_cart) %> </p>

app/views/products/new.html.erb
<h2> 商品追加 </h2>

<%= form_for @product, url: { action: :create } do |f| %>
    <p>
        <%= f.label :name, '商品名' %>
        <%= f.text_field :name %>
    </p>
    <p>
        <%= f.label :price, '価格' %>
        <%= f.number_field :price %>
    </p>
    <%= f.submit '商品を追加する' %>
<% end %>

<p> <%= link_to '商品一覧' , products_path %> </p>
<p> <%= link_to 'カートを見る' , cart_path(current_cart) %> </p>